#!/bin/bash

# v0.2.1

# https://en.wikipedia.org/wiki/Solstice
# http://stackoverflow.com/q/1579587/1248177
# http://www.developpez.net/forums/d880640/java/general-java/calcul-saisons/
# http://www.jgiesen.de/astro/astroJS/seasons/seasons.js

# http://stackoverflow.com/q/1579587/1248177
# no native floating point in bash so n*100
# https://lists.gnu.org/archive/html/bug-bash/2009-11/msg00009.html
#  bash dont know how to handle leading zeros
function getSeason {
	readonly month=$(date "+%m")
	readonly day=$(date "+%d")

	readonly dateAsInt=$(( 10#$month * 100 + 10#$day))
	if [ $dateAsInt -lt 321 ] || [ $dateAsInt -ge 1222 ]; then
		echo "Winter"
	elif [ $dateAsInt -lt 621 ]; then
		echo "Spring"
	elif [ $dateAsInt-lt 923 ]; then
		echo "Summer"
	else
		echo "Autumn"
	fi
}

function extractUrl {
	# get json
	curl -s "$1" |
	# extract all url
	grep -Po '"url":.*?[^\\]",' |
	# remove each one who contains reddit
	grep -v "reddit" |
	# keep direct url (no flickr...)
	grep -Po '\bhttps?:[^)"]+\.(?:jpg|jpeg|png)' |
	# keep first
	(head -n1 && tail -n1)
}

# Get season
readonly season=$(getSeason)

# Get image url from Reddit
readonly imageSource=$(extractUrl "https://www.reddit.com/r/${season}Porn.json")

# Print image source
echo "$imageSource"