#!/bin/bash

# v0.2.0

# https://en.wikipedia.org/wiki/Solstice
# http://www.developpez.net/forums/d880640/java/general-java/calcul-saisons/
# http://www.jgiesen.de/astro/astroJS/seasons/seasons.js
# http://stackoverflow.com/q/1579587/1248177

# http://stackoverflow.com/q/1579587/1248177
# no native floating point in bash so n*100
function getSeason {
	readonly month=$(date "+%m")
	readonly day=$(date "+%d")
	readonly dateAsInt=$(($((month + $((day / 100)))) * 100))
	
	if [ $dateAsInt -lt 321 ] || [ $dateAsInt -ge 1222 ]; then
		echo "Winter"
	elif [ $dateAsInt -lt 621 ]; then
		echo "Spring"
	elif [ $dateAsInt-lt 923 ]; then
		echo "Summer"
	else
		echo "Autumn"
	fi
}

function extractUrl {
	# get json
	curl -s "$1" |
	# extract all url
	grep -Po '"url":.*?[^\\]",' |
	# remove each one who contains reddit
	grep -v "reddit" |
	# keep direct url (no flickr...)
	grep -Po '\bhttps?:[^)"]+\.(?:jpg|jpeg|png)' |
	# keep first
	(head -n1 && tail -n1)
}

# Get season
readonly season=$(getSeason)

# Get image url from Reddit
readonly imageSource=$(extractUrl "https://www.reddit.com/r/EarthPorn.json")
# readonly imageSource=$(extractUrl "https://www.reddit.com/r/${season}Porn.json")

# Set the picture as wallpaper

echo "$imageSource"
# 
# readonly filename=$(basename "$imageSource")
# readonly extension="${filename##*.}"
# 
# wget -q --show-progress "$imageSource" --output-document "/tmp/seasonpaper.$extension" 
# 
feh --bg-fill $imageSource